name: tripmate
description: A travel guidance application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flushbar: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.0+1
  provider: ^4.0.5+1
  flutter_spinkit: "^4.1.2"

flutter:
  uses-material-design: true
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
  assets:
    - assets/images/